#Indexed Color Using Octree 
#Rongzhong Li
#March 8
run:	idxC
	./idxC WhiteRose.raw 400 300

idxC: 	main.cpp octree.h io.h
	g++ -o idxC main.cpp octree.h io.h
	
clean:
	rm -f *~ idxC

  
